name: Dynamic Matrix Example

on: workflow_dispatch

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Define Matrix Without jq
        id: set-matrix
        run: |
          # Create the matrix for project
          matrix='[{"project":"amp"},{"project":"amp1"}]'
          echo "::set-output name=matrix::$matrix"

  run-parallel:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        project: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
        zone: [e1, e2]  # Static zone values, as dynamic zones in matrix aren't supported

    steps:
      - name: Print Project and Zone
        run: |
          echo "Project: ${{ matrix.project }} | Zone: ${{ matrix.zone }}"
