name: Parallel Jobs Example

on: workflow_dispatch

jobs:
  list_projects:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}

    steps:
      - name: Define Projects Variable
        id: set-matrix
        run: |
          file='["amp1","amp2","amp3","amp4"]'
          echo "::set-output name=projects::$file"

  Health_pod_check:
    runs-on: ubuntu-latest
    needs: list_projects
    strategy:
      matrix:
        project: ${{ fromJson(needs.list_projects.outputs.projects) }}
        zone: [e1, e2]

    steps:
      - name: Print Project and Zone
        run: |
          echo "Project: ${{ matrix.project }} | Zone: ${{ matrix.zone }}"
          echo " ${{ matrix.project }}_${{ matrix.zone }} is creating the file" >> ${{ matrix.project }}_${{ matrix.zone }}.json
           echo " ***************************************************** "
           cat ${{ matrix.project }}_${{ matrix.zone }}.json

      - name: Upload JSON File as Artifact-${{ matrix.project }}_${{ matrix.zone }}.json
        uses: actions/upload-artifact@v3
        with:
          name: healthcheck
          path: ./${{ matrix.project }}_${{ matrix.zone }}.json


  download-and-publish-json:
    runs-on: ubuntu-latest
    needs: Health_pod_check

    steps:
      - name: Download JSON Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-custom-json-file
          path: ./

      - name: Publish JSON Contents
        run: |
          echo "Publishing the following JSON file content:"
          pwd
          ls -latr
          cd healthcheck
          ls -latr
          pwd
          
          
