name: Parallel Jobs Example

on: workflow_dispatch

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}  # Define output for matrix

    steps:
      - name: Define Projects List
        id: set-matrix
        run: |
          projects='["amp1","amp2","amp3","amp4"]'
          echo "PROJECTS=$projects" >> $GITHUB_ENV  # Write to GITHUB_ENV instead of using set-output

  run-parallel:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        project: ${{ fromJson(needs.define-matrix.outputs.projects) }}  # Use job output for matrix
        zone: [e1, e2]

    steps:
      - name: Print Project and Zone
        run: |
          echo "Project: ${{ matrix.project }} | Zone: ${{ matrix.zone }}"
          echo " ${{ matrix.project }}_${{ matrix.zone }} is creating the file" >> ${{ matrix.project }}_${{ matrix.zone }}.json
          echo " ***************************************************** "
          cat ${{ matrix.project }}_${{ matrix.zone }}.json
