name: Main Workflow - Trigger Reusable

on:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}

    steps:
      - name: Define Projects List
        id: set-matrix
        run: |
          projects='["amp1","amp2","amp3","amp4"]'
          echo "projects=$projects" >> $GITHUB_OUTPUT

  trigger-reusable:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        project: ${{ fromJson(needs.define-matrix.outputs.projects) }}
        zone: [e1, e2]

    steps:
      - name: Call Reusable Workflow
        uses: dileep963/test@main  # Replace with your repository and branch
        with:
          workflow: .github/workflows/reusable-create-json.yml  # Path to the reusable workflow
          project: ${{ matrix.project }}
          zone: ${{ matrix.zone }}
