name: APITEST
on:
  workflow_dispatch:
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
       - name: Run custom action to fetch workflow jobs
         uses: dileep963/test/history@main
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           repo: 'your_owner/your_repo'
           workflow_name: 'workflow_name.yml'
           duration: '2w'
           exclude_overall_status: queued
          
       - name: file check
         run: | 
              ls -altr
              pwd
              cat output.json
         
  
  
