name: APITEST
on:
  workflow_dispatch:
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
       - name: Run custom action to fetch workflow jobs
         uses: dileep963/test/history@main
         with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            workflow_name: "manual-trigger.yml"
            repo: "dileep963/test"
            duration: "1m"
            output_file: "output.json"
            exclude_statuses: "cancelled, success"  # Example: excluding queued and failure statuses
          
       - name: file check
         run: | 
              ls -altr
              pwd
              cat output.json
         
  
  
