name: APITEST
on:
  workflow_dispatch:
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
       - name: Run custom action to fetch workflow jobs
         uses: dileep963/test/history@main
         with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            runs_api: "https://api.github.com/repos/dileep963/test/actions/workflows/manual-trigger.yml/runs?per_page=5"
            jobs_api: "https://api.github.com/repos/dileep963/test/actions/runs"
