name: Zones Workflow

on:
  workflow_call:
    inputs:
      zoneslist:
        description: 'The list of zones'
        required: true
      zone_level:
        description: 'The level of the zone'
        required: false
        default: 'level1'
    type: workflow 

jobs:
  list_projects:
    runs-on: aexp-ubuntu-latest-medium
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}
    steps:
      - name: Define Projects Variable
        id: set-matrix
        run: |
          file='["amp-pos", "amp-nonpos"]'
          echo "projects=$file" >> $GITHUB_OUTPUT
         
  Health_pod_check:
    runs-on: ubuntu-latest
    needs: list_projects
    strategy:
      matrix:
        project: ${{ fromJson(needs.list_projects.outputs.projects) }}
        zone: {{ inputs.zoneslist }}
    steps:
      - name: Check Pod Health
        run: |
          echo "Checking health for project: ${{ matrix.project }} in zone: ${{ matrix.zone }}"
          # Add your logic for pod health checks
