name: Reusable Workflow - Create JSON Files

on:
  workflow_call:
    inputs:
      project:
        description: "The project name"
        required: true
        type: string
      zone:
        description: "The zone name"
        required: true
        type: string

jobs:
  create-json:
    runs-on: ubuntu-latest

    steps:
      - name: Print Project and Zone
        run: |
          echo "Project: ${{ inputs.project }} | Zone: ${{ inputs.zone }}"
          echo "{ \"project\": \"${{ inputs.project }}\", \"zone\": \"${{ inputs.zone }}\" }" > ${{ inputs.project }}_${{ inputs.zone }}.json
          echo "Created file: ${{ inputs.project }}_${{ inputs.zone }}.json"
          echo "*****************************************************"
          cat ${{ inputs.project }}_${{ inputs.zone }}.json
